### ISSUE TITLE
Bug in SAP biden task: field needs to be longer

### ISSUE THREAD

**Issue by aih** [aih/BillMap#562]
I ran the latest sap_biden_task and got the following error:

```log
Received task: bills.tasks.sap_biden_task[af00304a-3be3-485b-b6db-f44115a2112e]
[2021-08-31 18:09:59,718: ERROR/ForkPoolWorker-1] Task bills.tasks.sap_biden_task[af00304a-3be3-485b-b6db-f44115a2112e] raised unexpected: DataError('value too long for type character varying(100)\n')
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
    self._pq_execute(self._query, conn._async)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
    self._pq_fetch()
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
    raise self._conn._create_exception(cursor=self)
psycopg2cffi._impl.exceptions.DataError: value too long for type character varying(100)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/flatgov/FlatGov/server_py/flatgov/bills/tasks.py", line 22, in sap_biden_task
    load_biden_statements()
  File "/opt/flatgov/FlatGov/server_py/flatgov/common/biden_statements.py", line 30, in load_biden_statements
    statement.save()
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
    self._pq_execute(self._query, conn._async)
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
    self._pq_fetch()
  File "/home/ubuntu/.pyenv/versions/3.8.3/envs/flatgov/lib/python3.8/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
    raise self._conn._create_exception(cursor=self)
django.db.utils.DataError: value too long for type character varying(100)
```

**Comment by aih** [comment]
As @ayeshamk suggested, I migrated the db according to the migration that was in the PR and now it works.
